"""Remove bio

Revision ID: 269c510b7404
Revises: 6064c5bfa791
Create Date: 2020-02-11 13:32:55.545698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269c510b7404'
down_revision = '6064c5bfa791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
